### ISSUE TITLE
Write tests for each step in the data workflow

### ISSUE THREAD

**Issue by scottwn** [AgnostiqHQ/covalent#146]
### What should we add?

Need tests for each of the following

- [x] validate source and destination
- [x] download
- [x] upload
- [ ] query workflows
- [x] query single workflow
- [x] check if workflow exists
- [x] return workflow

**Comment by scottwn** [comment]
Iceboxing this awaiting design changes per @kessler-frost and @AlejandroEsquivel

**Comment by AlejandroEsquivel** [comment]
The changes that we made were around the endpoints of the Data Component / Service, namely we're assuming the Data component will "own" the results object db.

As a result of this, other components / services will need to query the Data Service to fetch ("download") the Result object,  POST ("upload") the Result object or PUT ("update") the Result object. Hence this is a restful approach to the Results resource.

This is essentially the same as the diagram just with the explicit mention of all CRUD operations on the result object (POST, PUT).

I'm not totally sure if the /download and /upload endpoints will be deprecated as a result or if they are meant to be general purpose to store other objects besides just the Result object, will need to defer that to @wjcunningham7  for confirmation.

The `307-os-skeleton` branch on the `covalent` repo has the most up-to-date api specs (wip) under the `refactor` folder.

**Comment by scottwn** [comment]
Summarizing the current state of the tests;

*DONE*
 - `GET` `/fs/download/` https://github.com/AgnostiqHQ/covalent/blob/i-146/refactor/data/tests/main_test.py#L46
 - `POST` `/fs/upload/` https://github.com/AgnostiqHQ/covalent/blob/i-146/refactor/data/tests/main_test.py#L28
 - `LocalStorageBackend.get()` https://github.com/AgnostiqHQ/covalent/blob/i-146/refactor/data/tests/app/core/localstoragebackend_test.py#L32
 - `LocalStorageBackend.put()` https://github.com/AgnostiqHQ/covalent/blob/i-146/refactor/data/tests/app/core/localstoragebackend_test.py#L37
 - `GET` `/workflow/results/{MOCK_DISPATCH_ID}` https://github.com/AgnostiqHQ/covalent/blob/i-146/refactor/results/tests/main_test.py#L37

**IN PROGRESS**
 - `POST` `/workflow/results` https://github.com/AgnostiqHQ/covalent/blob/i-146/refactor/results/tests/main_test.py#L52 (this test currently hangs and needs further debugging)

**TODO**
 - `PUT` `/workflow/results/{MOCK_DISPATCH_ID}`
 - `Database.value`
 - `StorageBackend` and `MinioStorageBackend`
 - internal functions?

**Comment by cjao** [comment]
Does `StorageBackend` need tests as an abstract class?

**Comment by scottwn** [comment]
> Does `StorageBackend` need tests as an abstract class?

I'm gonna say no

**Comment by cjao** [comment]
Some notes on the failing `POST /workflow/results` test:

Uploading the results pickle file fails at [this line](https://github.com/AgnostiqHQ/covalent/blob/i-146/refactor/results/app/api/api_v0/endpoints/workflow.py#L98), which unpickles the file to extract the `dispatch_id` from the result object. Unfortunately, this requires the results service to satisfy the module dependencies of `Result.lattice`. In the test, the lattice depends on `sklearn`, which is not installed in the results service's environment.

Is it possible to avoid unpickling the result object by intermediate services? Or is there an alternative to `cloudpickle` that doesn't try to import all of the module dependencies of a pickle file?

**Comment by scottwn** [comment]
@cjao how is this going? do you want me to keep going on it or should I reassign it to you?

**Comment by cjao** [comment]
I can finish the remaining tests.
