### ISSUE TITLE
Nightly builds

### ISSUE THREAD

**Issue by scottwn** [AgnostiqHQ/covalent#448]
- [x] Create nightly tests that run and trigger a prerelease if they pass
- [x] Don't run tests automatically on every push to develop
- [x] Reduce the scope of tests that run on PRs; they should only be unit tests and only unit tests for services that were changed
- [x] Create a manual trigger for tests in `develop`
- [ ] Versioning for services
- [ ] Run the tutorials as part of the nightly test
- [x] Automate Conda deployment

**Comment by scottwn** [comment]
CI redesign doc https://docs.google.com/document/d/1rE_eVhzkb0syRK877SvppxH43iLoxhM9xphJayfGs2Y/edit
cc @santoshkumarradha @wjcunningham7

**Comment by scottwn** [comment]
Updated CI nightly design https://www.notion.so/Executor-Plugin-CI-5c702cfe221f4b11be23a148e4551a78#e8305b6d492748e78fcfa8b3483dc520

**Comment by venkatBala** [comment]
Acceptance criteria

- [ ] Curate a stable environment to run performance benchmarks on nightly

- [ ] Update the stress tests to report results in a uniform manner so that they can be post-processed afterwards

- [ ] Run load tests and generate results

- [ ] Sketch out high level nightly benchmark pipeline in order to clearly layout the distinct stages, workflow, artifacts and archival

- [ ] Generate concise reports from nightly runs (performance stress tests and load tests) that can be assessed at a later date

**Comment by scottwn** [comment]
Diagram showing nightly flow https://drive.google.com/file/d/1Mwv-JYSPT6rrznVb_Erjwxa2c1zRRYLi/view?usp=sharing

**Comment by scottwn** [comment]
more notes on nightly logic https://agnostiqworkspace.slack.com/files/TN18FBMMY/F03UU340G3D
