### ISSUE TITLE
More efficient continuous parallel executions of electrons in a lattice (beyond topological sort)

### ISSUE THREAD

**Issue by santoshkumarradha** [AgnostiqHQ/covalent#651]
## Overview

Currently, we dispatch electrons parallelly using the topologically sorted graph where each "set" of electrons is being run parallelly. Instead, we can run things faster if we recheck the dependencies each time based on completed electrons. 

Consider the following graph.
![output](https://user-images.githubusercontent.com/29346072/146657742-c508bf9e-13be-49af-b34e-d80dc0e61ef4.png)

Topological sorted values are
`[[0, 1, 2], [3, 4], [5, 9]]`

So right now we run things such that `[0,1,2]`  are sent parallelly. We wait for all of them to finish and then we go to `[3,4]` wait for all of them to finish.. etc.

Now consider the scenario where in the first run `[0,2]` nodes are done. We can in theory go on to `4` even though `1` is not completed. We are assuming in the current implementation that all electrons require an equal amount of time and hence all parallelly sent jobs to complete equally at the same time.  

![output1](https://user-images.githubusercontent.com/29346072/146657838-8466244e-9168-4f4f-9551-accf536fe270.png)

Solution : Algorithm should be changed to the following
- First parallely execute the first topological electrons i.e.`[0,1,2]`
- As you get back result for each electron, run the following depedency function  on the graph where we have marked `G.nodes[completed_electron_node][completed]=True` (set that this node has indeed finished, we can use the result status of this electron to check it as well)
```python
def give_me_next_nodes(G):
    next_set=[]
    for i in G.nodes:
        if G.nodes[i].get('completed'):
            for children in list(nx.dfs_tree(G,i,1))[1:]:
                can_be_added=True
                for parent in list(nx.dfs_tree(G.reverse(), source=children,depth_limit=1).reverse())[1:]:
                    if not G.nodes[parent].get('completed'):can_be_added=False
                if can_be_added and not G.nodes[children].get('completed'):
                    next_set.append(children)
    return np.unique(next_set)
print(give_me_next_nodes(G))
```
- Run the list of nodes generated by `give_me_next_nodes(G)` in parallel and keep doing it.

This will now output `[4]` for a graph with `G[0]` and `G[2]` set to completed. 

Of course, this is just a basic function and in the actual issue, a more robust check for running nodes, etc.. needs to happen.

**Comment by venkatBala** [comment]
Acceptance criteria

- [ ] Review @cjao implementation

- [ ] Modify/update if necessary

- [ ] Ensure all tests run and pass

- [ ] Ensure all tutorials run
