### ISSUE TITLE
Covalent Benchmarking Post Result Object Decomposition

### ISSUE THREAD

**Issue by AlejandroEsquivel** [AgnostiqHQ/covalent#819]
## Acceptance Criteria

- Benchmark with .110
- Benchmark after topological sort, asyncio + result DB which would be the performance improvement in this release
- Update RTD & README (verify with @wjcunningham7) citing metrics that indicate performance benefits due to new version of covalent (post db)

**Comment by scottwn** [comment]
result DB is https://github.com/AgnostiqHQ/covalent/releases/tag/v0.136.0

**Comment by venkatBala** [comment]
- [ ] Create simple horizontal and fully vertical workflows
- [ ] Run workflows + measure execution time
- [ ] Create speedup plots

**Comment by venkatBala** [comment]
results: https://docs.google.com/presentation/d/1AfprijcWferKFT8lhcgq2wYqrp01VP80hVoXflt1D6I/edit#slide=id.g13e0d83d032_0_133

**Comment by scottwn** [comment]
I love these graphs🤩

**Comment by scottwn** [comment]
@venkatBala assuming #912 and #913 are done, can you put comments/links on them, move them to Review, and then ping me?
